name: Release

on:
  release:
    types: [published]

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t onsdigital/eq-questionnaire-validator:$GITHUB_REF .
      - name: Push
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          echo "Pushing with tag [$GITHUB_REF]"
          docker push onsdigital/eq-questionnaire-validator:$GITHUB_REF